### ISSUE TITLE
As a BBC website user I want to be able to enter a nickname so that I can be included in the quiz league table

### ISSUE THREAD

**Issue by jgra0907** [callumjfortune/BBCquiz#11]
Questions:
- How long would you like us to remember the nickname 
- Do you want your nickname to be unique
- Do you want to be included automatically in the league table

Acceptance Criteria:
- Forever, so that it is there when i next go to the quiz website
- Yes
- No, I want to chose whether my results are included

**Comment by bbcjl** [comment]
League table built and just waiting on nickname setting UI. Basically just register a user by running `registerUser`

```javascript
api.registerUser(theNicknameString).then(function() {
    // done, like idk redirect
}).catch(function() {
    // it's all gone wrong (basically user with same nickname already exists) so idk show error message
});
```
