### ISSUE TITLE
As a BBC Content Commissioner I want metrics from the website so that I can use those metrics to help me understand audience interests

### ISSUE THREAD

**Issue by jgra0907** [callumjfortune/BBCquiz#5]
Questions
- What Metrics do you want collected for Topics, Formats, and Levels
- How do you want the metrics reported
- DO you want user personal data collected

Acceptance Criteria
- For Topics: How often each topic is selected and what time of day it is selected
- For Formats: What formats were used, how many times they were used
- For Level of Difficulty: What level of difficulty is selected for each topic
- Metrics can be accessed by the commissioning team from a separate application(out of scope for this website development project)
- No personal data is needed

- [x] #16
- [x] #15
- [x] #14

**Comment by jgra0907** [comment]
- [ ] As a BBC Content Commissioner I want metrics from the website showing how often each topic is selected and what time of day it is selected so that I can understand audience interests
- [ ] As a BBC Content Commissioner I want metrics from the website showing what formats were used, how many times they were used so that I can understand audience interests
- [ ] As a BBC Content Commissioner I want metrics from the website showing what level of difficulty is selected for each topic  so that I can understand audience interests

**Comment by bbcjl** [comment]
Taking over due to Callum being away right now!

**Comment by jgra0907** [comment]
Completed MVP tasks. Moving to Could Have
